language: go

go:
  - 1.9.4

addons:
  apt:
    packages:
      - python-pygments

env:
  global:
    - COMMIT_AUTHOR_EMAIL: oriol.mauri@devcows.com
    - ENCRYPTION_LABEL: 7adb43d426f2

before_install:
  - export GOPATH=$HOME/go
  - export PATH=$PATH:$GOPATH/bin
  - sudo apt update
  - sudo apt install snapd

install:
  - snap install hugo

before_script:
  - mkdir themes
  - git clone --depth 1 https://github.com/maguri/acadir-theme.git themes/acadir-theme/

script:
  - hugo

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN
  on:
    branch: master

notifications:
  slack: devcows:bJqjHDL6xXdgga0I5r0yzM7z
