language: go
go:
- 1.12
addons:
  apt:
    packages:
    - python-pygments
env:
  global:
  - COMMIT_AUTHOR_EMAIL: oriol@bmauri.com
  - ENCRYPTION_LABEL: 7adb43d426f2
before_install:
- export GOPATH=$HOME/go
- export PATH=$PATH:$GOPATH/bin
- export HUGO_BIN=hugo_extended_0.66.0_Linux-64bit.tar.gz
install:
- wget https://github.com/gohugoio/hugo/releases/download/v0.66.0/$HUGO_BIN
- tar -xvf $HUGO_BIN
- sudo mv hugo /usr/bin/
before_script:
- mkdir $TRAVIS_BUILD_DIR/themes
- git clone --depth 1 https://github.com/maguri/acadir-theme.git $TRAVIS_BUILD_DIR/themes/acadir-theme/
script:
- hugo -s $TRAVIS_BUILD_DIR
- echo "www.aikidotarragona.org" >> $TRAVIS_BUILD_DIR/public/CNAME
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
