baseurl = "http://www.aikidotarragona.org"
title = "ACADIR"
theme = "acadir-theme"
languageCode = "en-us"
defaultContentLanguage = "cat"
# enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = "Associació Catalana d'Aikido Dento Iwama Ryu<br />"
  logoimage = "images/logo.svg"
  baseicon = "https://raw.githubusercontent.com/maguri/acadir/master/static/images/logo.ico"
  copyright = "ACADIR"
  developer = "maguri"
  github = "https://github.com/maguri"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/aikidoacadir/"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://twitter.com/aikidotgn/"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "https://www.instagram.com/acadir2007/"

[[params.social]]
  medium = "google-plus"
  icon = "google-plus"
  link = "https://plus.google.com/u/0/107719984313749568770"

[languages]
[languages.cat]
languageName = "Català"
weight = 4

# [languages.es]
# languageName = "Español"
# weight = 4
# description = '<!--[-->A fully responsive site template designed by <a href="https://html5up.net">HTML5 UP</a> and released<!--]--><br />
#                 <!--[-->for free under the <a href="https://html5up.net/license">Creative Commons</a> license.<!--]-->'
#
# [languages.en]
# languageName = "English"
# weight = 4
# description = '<!--[-->A fully responsive site template designed by <a href="https://html5up.net">HTML5 UP</a> and released<!--]--><br />
#                 <!--[-->for free under the <a href="https://html5up.net/license">Creative Commons</a> license.<!--]-->'
