baseurl = "http://www.aikidotarragona.org"
theme = "acadir-theme"
languageCode = "en-us"
defaultContentLanguage = "cat"
googleAnalytics = "UA-115814963-1"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  title = "ACADIR"
  description = "Associació Catalana d'Aikido Dento Iwama Ryu<br />"
  logoimage = "images/logo.svg"
  baseicon = "https://raw.githubusercontent.com/maguri/acadir/master/static/images/favicon.ico"
  copyright = "ACADIR"
  developer = "maguri"
  cv = "https://maguri.github.io/cv/"

[[params.social]]
  medium = "Facebook Aikido Tarragona"
  icon = "facebook"
  link = "https://www.facebook.com/aikidoacadir/"

[[params.social]]
  medium = "Instagram Aikido Tarragona"
  icon = "instagram"
  link = "https://www.instagram.com/acadir_tarragona/"

[[params.social]]
  medium = "Twitter Aikido Tarragona"
  icon = "twitter"
  link = "https://twitter.com/aikidotgn/"

[[params.social]]
  medium = "YouTube Aikido Tarragona"
  icon = "youtube"
  link = "https://www.youtube.com/channel/UCSAchRaks4wRy8VRAV4jnSg/"

[[params.media]]
  title = "Àlbum"
  subtitle = "Aikido Tarragona"
  medium = "Album Aikido Tarragona"
  icon = "photo"
  link = "https://sites.google.com/view/aikidotarragona/"

[languages]
[languages.cat]
languageName = "Català"
weight = 4

# [languages.terms]
# languageName = "Terms"
# weight = 1
# description = '<!--[-->A fully responsive site template designed by <a href="https://html5up.net">HTML5 UP</a> and released<!--]--><br />
#                 <!--[-->for free under the <a href="https://html5up.net/license">Creative Commons</a> license.<!--]-->'
#
# [languages.en]
# languageName = "English"
# weight = 4
# description = '<!--[-->A fully responsive site template designed by <a href="https://html5up.net">HTML5 UP</a> and released<!--]--><br />
#                 <!--[-->for free under the <a href="https://html5up.net/license">Creative Commons</a> license.<!--]-->'
