baseurl = "https://maguri.github.io/acadir/"
title = "Acadir"
baseicon = "${baseurl}images/logo.ico"
theme = "acadir-theme"
languageCode = "en-us"
defaultContentLanguage = "cat"
# enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = 'Descripció ACADIR<br />'
  logoimage = "images/logo.svg"
  copyright = "Oriol Mauri"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "#"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "#"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "#"

[[params.social]]
  medium = "file-image-o"
  icon = "file-image-o"
  link = "#"

[[params.social]]
  medium = "file-text"
  icon = "file-text"
  link = "#"
[languages]
[languages.cat]
languageName = "Català"
weight = 4

# [languages.es]
# languageName = "Español"
# weight = 4
# description = '<!--[-->A fully responsive site template designed by <a href="https://html5up.net">HTML5 UP</a> and released<!--]--><br />
#                 <!--[-->for free under the <a href="https://html5up.net/license">Creative Commons</a> license.<!--]-->'
#
# [languages.en]
# languageName = "English"
# weight = 4
# description = '<!--[-->A fully responsive site template designed by <a href="https://html5up.net">HTML5 UP</a> and released<!--]--><br />
#                 <!--[-->for free under the <a href="https://html5up.net/license">Creative Commons</a> license.<!--]-->'
